apiVersion : apps/v1
kind: Deployment
metadata:
  name: parulazuredevops 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: parulazuredevops 
    spec:
      containers:
        - name: parulazuredevops 
          image: mycontainerregistry818.azurecr.io/parulazuredevops
          ports:
          - containerPort: 8080
